Issue 414 flexible text enchancement
AAVSO/VStar pull request #417
Opened 2024-04-25 16:31 UTC by mpyat2

See #414

2024-04-25 20:00 UTC, mpyat2 commented
Hi @dbenn , please do not close this pull request, I found a small glitch and want to fix it first.

2024-04-26 06:09 UTC, mpyat2 commented
Hi again @dbenn :)

I fixed the glitch, so now the branch is ready for review

2024-04-27 04:52 UTC, dbenn requested changes
Hi @mpyat2, thanks for this. One suggested possible refactoring; see comment inline.

2024-04-27 04:52 UTC, dbenn commented on plugin/src/org/aavso/tools/vstar/external/plugin/FlexibleTextFileFormatObservationSink.java
> +		return field.contains(delimiter) ? quoteForCSV(field) : field;
An opportunity for refactoring here since `ValidObservation` has `quoteForCSVifNeeded` and `quoteForCSV` now I think?

2024-04-27 16:34 UTC, mpyat2 commented
Hi @dbenn , thank you for the suggestion!
You are right; making ValidObservation.quoteForCSVifNeeded(...) _public_ _static_ allows us to eliminate code duplication.
However, now this method is in the parallel universe of the other branch, creating a quantum wormhole between them may lead to something unpredictable (sorry, I'm reading Dan Simmons' Ilium/Olympos cosmic opera now and some nonsense comes into my head :) ). So, it would probably be better to make a new branch after merging this one, and I will refactor the code. What do you think?

2024-04-28 01:02 UTC, dbenn commented
Agreed. That sounds good @mpyat2

2024-04-28 01:08 UTC, merged